import { getTranslator } from '@/lib/i18n/server';
import Link from 'next/link';
export async function generateMetadata(){const tr=await getTranslator();return {
  title: tr('Privacidad')
};}
export default async function Privacy() {
  const tr = await getTranslator();
  return <main id="main" className="legal"><Link href="/">{tr("Volver al inicio")}</Link><p className="eyebrow">{tr("Privacidad · etapa de preparación")}</p><h1>{tr("Vos decidís")}<br />{tr("qué compartir.")}</h1><p>{tr("El registro público está cerrado mientras se completa la identificación del responsable y la política legal de lanzamiento. Esta página describe la implementación, pero no sustituye ese documento.")}</p><h2>{tr("Datos de cuenta")}</h2><p>{tr("Al habilitar el registro con Google, el proveedor de autenticación gestiona el identificador y el correo de la cuenta. El correo no forma parte del perfil visible. No almacenamos tu contraseña de Google.")}</p><h2>{tr("Tu mundo")}</h2><p>{tr("El perfil empieza privado. Podés compartirlo con personas registradas y controlar por separado visitados y wishlist. Las colecciones son privadas. Los mensajes se limitan a Co-Travelers y no son cifrados de extremo a extremo.")}</p><h2>{tr("Horas y ubicación")}</h2><p>{tr("Las horas son opcionales y privadas. La carga manual no solicita rutas, fechas, reservas ni GPS. No hay estado online o última conexión. Las fotos se vuelven a codificar para eliminar metadatos antes de almacenarlas.")}</p><h2>{tr("Proveedores y cookies")}</h2><p>{tr("La versión configurada utiliza Vercel para alojar la web, Supabase para autenticación, datos y archivos, Google para iniciar sesión y Redis de Upstash para limitar intentos de acceso. Utiliza cookies de sesión necesarias. No incorpora analítica publicitaria.")}</p><h2>{tr("Control de tus datos")}</h2><p>{tr("Mi perfil permite descargar los datos y eliminar la cuenta. La eliminación de backups depende de los plazos del proveedor, que deben documentarse antes del lanzamiento.")}</p><p>{tr("Antes de abrir el registro se publicarán responsable, contacto, jurisdicción, edades permitidas, retención y mecanismos de ejercicio de derechos.")}</p></main>;
}
